clusterlist => ['gram5.ceres.auckland.ac.nz'],
    uids =>  {
   Site => [ "auckland.ac.nz", ],
   SubCluster => [ "gram5.ceres.auckland.ac.nz-subcluster-GT5", ],
   Cluster => [ "gram5.ceres.auckland.ac.nz", ],
   ComputingElement => [ "gram5.ceres.auckland.ac.nz-ce-GT5", 
			 "gram5.ceres.auckland.ac.nz-uoaMechCE",
			 "gram5.ceres.auckland.ac.nz-uoaEvolCE",
			 "gram5.ceres.auckland.ac.nz-uoaEngSciCE",
			 "gram5.ceres.auckland.ac.nz-uoastats",
			 "gram5.ceres.auckland.ac.nz-uoacompchem",
			 "gram5.ceres.auckland.ac.nz-uoamath",
			 "gram5.ceres.auckland.ac.nz-uoaqoptics",
			 "gram5.ceres.auckland.ac.nz-demo",
			 "gram5.ceres.auckland.ac.nz-gpu",
			 "gram5.ceres.auckland.ac.nz-gold",
			 ],
   StorageElement => [ "gram5.ceres.auckland.ac.nz", ],
}
